"use client";
import{useEffect,useState}from"react";import AdminSidebar from"@/components/AdminSidebar";
export default function EditProduct({params}:{params:Promise<{id:string}>}){const[id,setId]=useState(""),[p,setP]=useState<any>(null),[categories,setCategories]=useState<any[]>([]),[imageUrl,setImageUrl]=useState(""),[imageAlt,setImageAlt]=useState(""),[msg,setMsg]=useState("");
useEffect(()=>{params.then(x=>{setId(x.id);fetch("/api/admin/products/"+x.id).then(r=>r.json()).then(setP);fetch("/api/admin/categories").then(r=>r.json()).then(setCategories)})},[]);
if(!p)return <div className="admin-layout"><AdminSidebar/><main className="admin-content"><div className="loading-skeleton" style={{height:180}}/></main></div>;
async function save(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/products/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:p.name,description:p.description,price:Number(p.price),compareAtPrice:p.compareAtPrice===""?null:p.compareAtPrice,salePrice:p.salePrice===""?null:p.salePrice,stock:Number(p.stock),lowStockThreshold:Number(p.lowStockThreshold),featured:!!p.featured,published:!!p.published,categoryId:p.categoryId||null})});setMsg(r.ok?"Saved successfully":"Save failed")}
async function addImage(e:React.FormEvent){e.preventDefault();if(!imageUrl)return;const r=await fetch("/api/admin/products/"+id+"/images",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:imageUrl,alt:imageAlt,sortOrder:p.images?.length||0})});if(r.ok){const d=await r.json();setP({...p,images:[...(p.images||[]),d]});setImageUrl("");setImageAlt("")}else setMsg("Image add failed")}
async function delImage(imageId:string){const r=await fetch("/api/admin/products/"+id+"/images?id="+encodeURIComponent(imageId),{method:"DELETE"});if(r.ok)setP({...p,images:(p.images||[]).filter((x:any)=>x.id!==imageId)})}
return <div className="admin-layout"><AdminSidebar/><main className="admin-content"><div className="admin-page-head"><div><a href="/admin/products">← Products</a><h1>Edit Product</h1><p>Update product information, pricing, stock and media.</p></div></div><section className="admin-card" style={{maxWidth:900}}><form onSubmit={save} style={{display:"grid",gap:14}}><input value={p.name} onChange={e=>setP({...p,name:e.target.value})}/><input value={p.sku} readOnly/><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}><input type="number" step=".01" value={p.price} onChange={e=>setP({...p,price:e.target.value})}/><input type="number" step=".01" value={p.compareAtPrice??""} placeholder="Compare-at price" onChange={e=>setP({...p,compareAtPrice:e.target.value})}/><input type="number" step=".01" value={p.salePrice??""} placeholder="Sale price" onChange={e=>setP({...p,salePrice:e.target.value})}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><input type="number" value={p.stock} onChange={e=>setP({...p,stock:e.target.value})}/><input type="number" min="0" value={p.lowStockThreshold} placeholder="Low-stock threshold" onChange={e=>setP({...p,lowStockThreshold:e.target.value})}/></div><select value={p.categoryId||""} onChange={e=>setP({...p,categoryId:e.target.value||null})}><option value="">No category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea value={p.description||""} rows={7} onChange={e=>setP({...p,description:e.target.value})}/><div style={{display:"flex",gap:20,flexWrap:"wrap"}}><label><input type="checkbox" checked={!!p.featured} onChange={e=>setP({...p,featured:e.target.checked})}/> Featured</label><label><input type="checkbox" checked={!!p.published} onChange={e=>setP({...p,published:e.target.checked})}/> Published</label></div><button style={{background:"#111827",color:"#fff"}}>Save Changes →</button>{msg&&<p>{msg}</p>}</form></section><section className="admin-card" style={{marginTop:20}}><h2>Product Images</h2><form onSubmit={addImage} style={{display:"grid",gap:10,maxWidth:600}}><input required placeholder="Image URL" value={imageUrl} onChange={e=>setImageUrl(e.target.value)}/><input placeholder="Alt text" value={imageAlt} onChange={e=>setImageAlt(e.target.value)}/><button>Add image</button></form><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(160px,1fr))",gap:12,marginTop:16}}>{(p.images||[]).map((i:any)=><article key={i.id}><img src={i.url} alt={i.alt||p.name} loading="lazy" decoding="async" style={{width:"100%",aspectRatio:"1",objectFit:"cover",borderRadius:8}}/><button onClick={()=>delImage(i.id)}>Delete</button></article>)}</div></section></main></div>}
