/* Firestore REST data layer. Cloudflare/Workers compatible; no firebase-admin dependency. */

type AnyObj=Record<string,any>;
function envValue(name:string){return String(process.env[name]||"").trim().replace(/^"([\\s\\S]*)"$/,"$1").replace(/^\'([\\s\\S]*)\'$/,"$1");}
function serviceAccountValue(name:string,field:string){
  const raw=envValue(name);
  if(raw.startsWith("{")){try{return String(JSON.parse(raw)[field]||"").trim();}catch{}}
  return raw;
}
const PROJECT=serviceAccountValue("FIREBASE_PROJECT_ID","project_id")||"e-commerce-bb2af";
const SA_EMAIL=serviceAccountValue("FIREBASE_CLIENT_EMAIL","client_email");
const SA_KEY=serviceAccountValue("FIREBASE_PRIVATE_KEY","private_key").replace(/^"([\\s\\S]*)"$/,"$1").replace(/^\'([\\s\\S]*)[\']$/,"$1").replace(/\\n/g,"\n").replace(/\\r/g,"\r").replace(/\r/g,"").trim();
const BASE=`https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents`;
let cachedToken:{token:string;exp:number}|null=null;

function b64url(input:ArrayBuffer|string){const bytes=typeof input==="string"?new TextEncoder().encode(input):new Uint8Array(input);let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
function pemBytes(pem:string){const normalized=pem.trim().replace(/\\n/g,"\n").replace(/\\r/g,"\r");const b64=normalized.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,"");const bin=atob(b64);const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a;}
async function accessToken(){const now=Math.floor(Date.now()/1000);if(cachedToken&&cachedToken.exp>now+60)return cachedToken.token;if(!SA_EMAIL||!SA_KEY)throw new Error("Firebase service account is not configured");const header=b64url(JSON.stringify({alg:"RS256",typ:"JWT"}));const payload=b64url(JSON.stringify({iss:SA_EMAIL,scope:"https://www.googleapis.com/auth/datastore",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3600}));const key=await crypto.subtle.importKey("pkcs8",pemBytes(SA_KEY),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(`${header}.${payload}`));const assertion=`${header}.${payload}.${b64url(sig)}`;const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:`grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${encodeURIComponent(assertion)}`});if(!r.ok)throw new Error(`Google token error ${r.status}`);const j:any=await r.json();cachedToken={token:j.access_token,exp:now+Number(j.expires_in||3600)};return j.access_token;}
async function req(path:string,init:RequestInit={}){const token=await accessToken();const r=await fetch(`${BASE}${path}`,{...init,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(init.headers||{})}});if(!r.ok){const t=await r.text();throw new Error(`Firestore ${r.status}: ${t}`)}return r.status===204?null:r.json();}
function enc(v:any):any{if(v===null||v===undefined)return {nullValue:null};if(v instanceof Date)return {timestampValue:v.toISOString()};if(typeof v==="string")return {stringValue:v};if(typeof v==="boolean")return {booleanValue:v};if(typeof v==="number")return Number.isInteger(v)?{integerValue:String(v)}:{doubleValue:v};if(Array.isArray(v))return {arrayValue:{values:v.map(enc)}};if(typeof v==="object")return {mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,enc(x)]))}};return {stringValue:String(v)};}
function dec(v:any):any{if(!v)return null;if("nullValue"in v)return null;if("stringValue"in v)return v.stringValue;if("booleanValue"in v)return v.booleanValue;if("integerValue"in v)return Number(v.integerValue);if("doubleValue"in v)return v.doubleValue;if("timestampValue"in v)return new Date(v.timestampValue);if("arrayValue"in v)return (v.arrayValue.values||[]).map(dec);if("mapValue"in v)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,dec(x)]));return null;}
function docToObj(d:any){return d?{id:d.name.split("/").pop(),...Object.fromEntries(Object.entries(d.fields||{}).map(([k,v])=>[k,dec(v)]))}:null;}
const collections:AnyObj={user:"users",category:"categories",product:"products",productImage:"productImages",wishlistItem:"wishlistItems",review:"reviews",paymentGateway:"paymentGateways",order:"orders",paymentTransaction:"paymentTransactions",stockReservation:"stockReservations",orderItem:"orderItems",coupon:"coupons",auditLog:"auditLogs"};
function cmp(a:any,b:any){if(a instanceof Date)a=a.getTime();if(b instanceof Date)b=b.getTime();return a<b?-1:a>b?1:0;}
function get(obj:any,key:string){return key.split(".").reduce((x,k)=>x?.[k],obj);}
function match(obj:any,where:any):boolean{if(!where)return true;if(where.AND)return where.AND.every((x:any)=>match(obj,x));if(where.OR)return where.OR.some((x:any)=>match(obj,x));if(where.NOT)return !match(obj,where.NOT);for(const [k,cond] of Object.entries(where)){const v=get(obj,k);if(cond&&typeof cond==="object"&&!Array.isArray(cond)){if("equals"in cond&&v!==cond.equals)return false;if("in"in cond&&!((cond as any).in as any[]).includes(v))return false;if("notIn"in cond&&((cond as any).notIn as any[]).includes(v))return false;if("contains"in cond&&!String(v??"").toLowerCase().includes(String((cond as any).contains).toLowerCase()))return false;if("startsWith"in cond&&!String(v??"").toLowerCase().startsWith(String((cond as any).startsWith).toLowerCase()))return false;if("gt"in cond&&!(v>(cond as any).gt))return false;if("gte"in cond&&!(v>=(cond as any).gte))return false;if("lt"in cond&&!(v<(cond as any).lt))return false;if("lte"in cond&&!(v<=(cond as any).lte))return false;}else if(v!==cond)return false;}return true;}
function stripData(data:any){const out={...data};for(const k of Object.keys(out))if(out[k]===undefined)delete out[k];return out;}
async function all(model:string){let token="";const out:any[]=[];do{const q=token?`?pageSize=1000&pageToken=${encodeURIComponent(token)}`:"?pageSize=1000";const j=await req(`/${collections[model]}${q}`);out.push(...(j.documents||[]).map(docToObj));token=j.nextPageToken||"";}while(token);return out;}
async function rawGet(model:string,id:string){try{return docToObj(await req(`/${collections[model]}/${encodeURIComponent(id)}`));}catch(e:any){if(String(e.message).startsWith("Firestore 404"))return null;throw e;}}
async function write(model:string,id:string,data:any){const fields=Object.fromEntries(Object.entries(stripData(data)).map(([k,v])=>[k,enc(v)]));return docToObj(await req(`/${collections[model]}/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({fields})}));}
async function remove(model:string,id:string){await req(`/${collections[model]}/${encodeURIComponent(id)}`,{method:"DELETE"});}
function id(){return crypto.randomUUID().replace(/-/g,"").slice(0,24);}
async function applyData(model:string,idv:string,data:any){const current=await rawGet(model,idv);const next:AnyObj={...(current||{}),...stripData(data)};for(const [k,v] of Object.entries(data)){if(v&&typeof v==="object"&&"increment"in v)next[k]=Number(current?.[k]||0)+Number((v as any).increment);if(v&&typeof v==="object"&&"decrement"in v)next[k]=Number(current?.[k]||0)-Number((v as any).decrement);}next.id=idv;return write(model,idv,next);}
const relationMap:any={user:{orders:["order","userId"],wishlist:["wishlistItem","userId"],reviews:["review","userId"]},category:{products:["product","categoryId"]},product:{category:["category","categoryId"],images:["productImage","productId"],items:["orderItem","productId"],reservations:["stockReservation","productId"],wishlist:["wishlistItem","productId"],reviews:["review","productId"]},productImage:{product:["product","productId"]},wishlistItem:{user:["user","userId"],product:["product","productId"]},review:{user:["user","userId"],product:["product","productId"]},paymentGateway:{orders:["order","paymentGatewayId"],transactions:["paymentTransaction","gatewayId"]},order:{user:["user","userId"],paymentGateway:["paymentGateway","paymentGatewayId"],items:["orderItem","orderId"],transactions:["paymentTransaction","orderId"],reservations:["stockReservation","orderId"]},paymentTransaction:{order:["order","orderId"],gateway:["paymentGateway","gatewayId"]},stockReservation:{order:["order","orderId"],product:["product","productId"]},orderItem:{order:["order","orderId"],product:["product","productId"]}};
function modelFor(obj:any){return obj?.__model||"";}
function applySelect(obj:any,sel:any){if(!sel)return obj;const o:any={};for(const k of Object.keys(sel))if(sel[k]&&k in obj)o[k]=obj[k];return o;}
function sortRows(rows:any[],order:any){if(!order)return rows;const arr=Array.isArray(order)?order:[order];return [...rows].sort((a,b)=>{for(const spec of arr){const [k,v]=Object.entries(spec)[0] as any;const c=cmp(get(a,k),get(b,k));if(c)return v==="desc"?-c:c;}return 0;});}
function withModel(row:any,m:string){return row?Object.assign(row,{__model:m}):row;}
async function include(obj:any,inc:any,select?:any){if(!obj)return obj;const out={...obj};for(const [rel,opt] of Object.entries(inc||{})){const cfg:any=opt||{};const map=relationMap[modelFor(obj)]?.[rel];if(!map)continue;const [m,f]=map as any;const one=["user","category","product","paymentGateway","order"].includes(rel);if(one){const rid=obj[f];const raw=rid?await rawGet(m,rid):null;out[rel]=raw?await include(withModel(raw,m),cfg.include,cfg.select):null;continue;}let matches=(await all(m)).filter((r:any)=>r[f]===obj.id);matches=sortRows(matches,cfg.orderBy);if(cfg.take)matches=matches.slice(0,cfg.take);out[rel]=await Promise.all(matches.map((x:any)=>include(withModel(x,m),cfg.include,cfg.select)));}return applySelect(out,select);}
async function query(model:string,args:any={}){let rows=(await all(model)).map(r=>withModel(r,model));rows=rows.filter(r=>match(r,args.where));rows=sortRows(rows,args.orderBy);if(args.skip)rows=rows.slice(args.skip);if(args.take!=null)rows=rows.slice(0,args.take);const result:any[]=[];for(const r of rows)result.push(await include(r,args.include,args.select));return result.map(r=>{if(r)delete r.__model;return r;});}
function compoundId(where:any){const vals=Object.values(where).flatMap((v:any)=>v&&typeof v==="object"&&!Array.isArray(v)?Object.values(v):[v]);return vals.map(v=>String(v)).join("__");}
async function resolve(model:string,where:any){if(where?.id)return rawGet(model,where.id);return (await query(model,{where,take:1}))[0]||null;}
function modelApi(model:string){return {findUnique:async(a:any={})=>resolve(model,a.where||{}).then((r:any)=>r?include(withModel(r,model),a.include,a.select):null),findFirst:async(a:any={})=>(await query(model,{...a,take:1}))[0]||null,findMany:async(a:any={})=>query(model,a),count:async(a:any={})=>(await query(model,{where:a.where})).length,aggregate:async(a:any={})=>{const rows=await query(model,{where:a.where});const out:any={};if(a._sum)for(const k of Object.keys(a._sum))out._sum={[k]:rows.reduce((s,r)=>s+Number(r[k]||0),0)};return out;},create:async(a:any={})=>{const i=a.data.id||id();const d={...a.data,id:i,createdAt:a.data.createdAt||new Date(),updatedAt:a.data.updatedAt||new Date()};const r=await write(model,i,d);return include(withModel(r,model),a.include,a.select);},createMany:async(a:any={})=>{for(const original of a.data||[]){const i=original.id||id();await write(model,i,{...original,id:i,createdAt:original.createdAt||new Date(),updatedAt:original.updatedAt||new Date()});}return {count:(a.data||[]).length};},update:async(a:any={})=>{const existing=await resolve(model,a.where||{});if(!existing)throw new Error("Not found");const r=await applyData(model,existing.id,{...a.data,updatedAt:new Date()});return include(withModel(r,model),a.include,a.select);},updateMany:async(a:any={})=>{const rows=await query(model,{where:a.where});for(const r of rows)await applyData(model,r.id,a.data);return {count:rows.length};},delete:async(a:any={})=>{const r=await resolve(model,a.where||{});if(!r)throw new Error("Not found");await remove(model,r.id);return r;},deleteMany:async(a:any={})=>{const rows=await query(model,{where:a.where});for(const r of rows)await remove(model,r.id);return {count:rows.length};},upsert:async(a:any={})=>{const r=await resolve(model,a.where||{});return r?modelApi(model).update({where:{id:r.id},data:a.update}):modelApi(model).create({data:{...a.create,id:compoundId(a.where||{})}});}};}
const db:any=new Proxy({}, {get:(_,model:string)=>modelApi(model)});
db.$transaction=async(fn:any)=>fn(db);
export {db};