"use client";
import{useEffect,useMemo,useState}from"react";import{getCart,saveCart,type CartItem}from"@/lib/cart";import Link from"next/link";import StoreHeader from"@/components/StoreHeader";import StoreFooter from"@/components/StoreFooter";
type Gateway={id:string;name:string;type:string;mode:string;qrImageUrl:string|null};
export default function Checkout(){
 const[items,setItems]=useState<CartItem[]>([]),[gateways,setGateways]=useState<Gateway[]>([]),[gatewayId,setGatewayId]=useState(""),[couponCode,setCouponCode]=useState(""),[form,setForm]=useState({customerName:"",customerPhone:"",customerEmail:"",shippingAddress:""}),[message,setMessage]=useState(""),[loading,setLoading]=useState(false),[gatewayLoading,setGatewayLoading]=useState(true);
 useEffect(()=>{setItems(getCart());fetch("/api/payment-gateways").then(r=>r.ok?r.json():[]).then((g:Gateway[])=>{const list=Array.isArray(g)?g:[];setGateways(list);if(list[0])setGatewayId(list[0].id)}).catch(()=>setGateways([])).finally(()=>setGatewayLoading(false))},[]);
 const subtotal=useMemo(()=>items.reduce((s,i)=>s+i.price*i.quantity,0),[items]);
 const shipping=subtotal>=3000?0:120;
 async function submit(e:React.FormEvent){e.preventDefault();if(!gatewayId||!items.length||loading)return;setLoading(true);setMessage("");let key=sessionStorage.getItem("checkout_idempotency_key");if(!key){key=crypto.randomUUID();sessionStorage.setItem("checkout_idempotency_key",key)}
 try{const res=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({...form,couponCode:couponCode.trim(),paymentGatewayId:gatewayId,items:items.map(i=>({productId:i.productId,quantity:i.quantity}))})});const data=await res.json();if(!res.ok){setMessage(data.error||"Order failed. Please try again.");return}sessionStorage.removeItem("checkout_idempotency_key");sessionStorage.setItem("lastOrderId",data.orderId);sessionStorage.setItem("orderPaymentToken",data.paymentToken||"");saveCart([]);window.location.href="/checkout/payment?order="+encodeURIComponent(data.orderId)}catch{setMessage("Unable to connect. Please check your internet connection and try again.")}finally{setLoading(false)}}
 return <><StoreHeader/><main className="checkout-page"><div className="checkout-steps"><span className="active">1. Information</span><span>2. Payment</span><span>3. Confirmation</span></div><div className="checkout-heading"><small>CHECKOUT</small><h1>Complete your order</h1><p>Enter your details and choose a payment method.</p></div>
 {!items.length?<section className="empty-state"><div className="empty-icon">🛒</div><h2>Your cart is empty</h2><p>Add products before starting checkout.</p><Link href="/products" className="primary-cta">Shop products</Link></section>:
 <div className="checkout-layout"><form onSubmit={submit} className="checkout-form"><h2>Customer information</h2><input required minLength={2} maxLength={100} placeholder="Full name" value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/><input required minLength={6} maxLength={30} placeholder="Phone number" value={form.customerPhone} onChange={e=>setForm({...form,customerPhone:e.target.value})}/><input type="email" maxLength={254} placeholder="Email (optional)" value={form.customerEmail} onChange={e=>setForm({...form,customerEmail:e.target.value})}/><textarea required minLength={5} maxLength={1000} placeholder="Full shipping address" rows={5} value={form.shippingAddress} onChange={e=>setForm({...form,shippingAddress:e.target.value})}/><div><label className="field-label">Coupon</label><input maxLength={50} placeholder="Coupon code (optional)" value={couponCode} onChange={e=>setCouponCode(e.target.value)}/></div><fieldset><legend>Payment method</legend>{gatewayLoading?<p>Loading payment methods...</p>:gateways.length?gateways.map(g=><label className="gateway-option" key={g.id}><input type="radio" name="gateway" checked={gatewayId===g.id} onChange={()=>setGatewayId(g.id)}/><span><b>{g.name}</b><small>{g.type}{g.mode==="SANDBOX"?" · Sandbox":""}</small></span></label>):<p>No payment method is currently available.</p>}</fieldset>{message&&<p className="form-error" role="alert">{message}</p>}<button disabled={loading||gatewayLoading||!gateways.length} type="submit">{loading?"Creating order...":"Continue to payment →"}</button></form>
 <aside className="checkout-summary"><small>ORDER SUMMARY</small><h2>৳{subtotal.toLocaleString("en-BD")}</h2><div className="checkout-summary-row"><span>Subtotal</span><b>৳{subtotal.toLocaleString("en-BD")}</b></div><div className="checkout-summary-row"><span>Shipping</span><b>{shipping===0?"Free":"৳"+shipping.toLocaleString("en-BD")}</b></div><div className="checkout-total"><span>Estimated total</span><strong>৳{(subtotal+shipping).toLocaleString("en-BD")}</strong></div><p>Any eligible coupon discount is applied by the order service and reflected in the final order before payment.</p><small>{items.length} item{items.length===1?"":"s"}</small></aside></div>}</main><StoreFooter/></>}
