import {NextRequest,NextResponse} from "next/server";import {db} from "@/lib/prisma";import {sendNewOrderTelegram,notifyStatus,telegramApi} from "@/lib/notifications/telegram-admin";
const allowed=(req:NextRequest)=>{const s=process.env.TELEGRAM_WEBHOOK_SECRET;return !s||req.headers.get("x-telegram-bot-api-secret-token")===s};
const admin=(q:any)=>String(q?.message?.chat?.id||"")===String(process.env.TELEGRAM_CHAT_ID||"");
export async function POST(req:NextRequest){try{if(!allowed(req))return NextResponse.json({ok:false},{status:401});const u=await req.json();const q=u.callback_query;if(!q)return NextResponse.json({ok:true});if(!admin(q)){await telegramApi("answerCallbackQuery",{callback_query_id:q.id,text:"Unauthorized",show_alert:true});return NextResponse.json({ok:true})}const data=String(q.data||""),[action,id]=data.split(":");const o=await db.order.findUnique({where:{id},include:{items:true,paymentGateway:true}});if(!o){await telegramApi("answerCallbackQuery",{callback_query_id:q.id,text:"Order not found",show_alert:true});return NextResponse.json({ok:true})}
if(action==="pay_confirm"){if(o.paymentStatus==="PAID"){await telegramApi("answerCallbackQuery",{callback_query_id:q.id,text:"Already paid",show_alert:true});return NextResponse.json({ok:true})}const ref=o.paymentReference||"TELEGRAM-"+Date.now();await db.$transaction(async tx=>{await tx.paymentTransaction.create({data:{orderId:o.id,gatewayId:o.paymentGatewayId!,reference:ref,amount:o.total,status:"PAID",rawResponse:{source:"telegram_admin_confirmation",telegramUserId:q.from?.id||null},verifiedAt:new Date()}});await tx.order.update({where:{id:o.id},data:{paymentStatus:"PAID",status:"CONFIRMED",paymentReference:ref}});await tx.stockReservation.updateMany({where:{orderId:o.id,status:"HELD"},data:{status:"CONFIRMED"}})});await telegramApi("answerCallbackQuery",{callback_query_id:q.id,text:"✅ Payment confirmed",show_alert:true});await notifyStatus(o.id)}
else if(action==="pay_reject"){if(o.paymentStatus==="PAID"){await telegramApi("answerCallbackQuery",{callback_query_id:q.id,text:"Cannot reject an already paid order",show_alert:true});return NextResponse.json({ok:true})}await db.order.update({where:{id:o.id},data:{paymentStatus:"FAILED",status:"CANCELLED"}});await db.stockReservation.updateMany({where:{orderId:o.id,status:"HELD"},data:{status:"RELEASED"}});await telegramApi("answerCallbackQuery",{callback_query_id:q.id,text:"❌ Payment rejected",show_alert:true});await notifyStatus(o.id)}
else if(action==="order_view"){const items=o.items.map(i=>"• "+i.name+" × "+i.quantity).join("\n");await telegramApi("sendMessage",{chat_id:process.env.TELEGRAM_CHAT_ID,text:"<b>Order Details</b>\nOrder: <code>"+o.orderNumber+"</code>\nCustomer: "+o.customerName+"\nPhone: <code>"+o.customerPhone+"</code>\nAddress: "+o.shippingAddress+"\nTotal: ৳"+Number(o.total).toLocaleString("en-BD")+"\nPayment: "+o.paymentStatus+"\nStatus: "+o.status+"\n\n"+items,parse_mode:"HTML"})}
else if(action==="status_menu"){await telegramApi("sendMessage",{chat_id:process.env.TELEGRAM_CHAT_ID,text:"Choose new status for <code>"+o.orderNumber+"</code>",parse_mode:"HTML",reply_markup:{inline_keyboard:[[{text:"✅ Confirmed",callback_data:"status:"+o.id+":CONFIRMED"},{text:"⚙️ Processing",callback_data:"status:"+o.id+":PROCESSING"}],[{text:"🚚 Shipped",callback_data:"status:"+o.id+":SHIPPED"},{text:"📬 Delivered",callback_data:"status:"+o.id+":DELIVERED"}],[{text:"❌ Cancelled",callback_data:"status:"+o.id+":CANCELLED"}]]}})}
else if(action==="status"){const next=data.split(":")[2];const valid=["CONFIRMED","PROCESSING","SHIPPED","DELIVERED","CANCELLED"];if(!valid.includes(next)){await telegramApi("answerCallbackQuery",{callback_query_id:q.id,text:"Invalid status",show_alert:true});return NextResponse.json({ok:true})}await db.order.update({where:{id:o.id},data:{status:next as any}});await telegramApi("answerCallbackQuery",{callback_query_id:q.id,text:"Status → "+next,show_alert:true});await notifyStatus(o.id)}
return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"Telegram bot processing failed"},{status:400})}}