import {NextRequest,NextResponse} from "next/server";import {db} from "@/lib/prisma";import {notifyStatus,telegramApi} from "@/lib/notifications/telegram-admin";
const allowed=(req:NextRequest)=>{const s=process.env.TELEGRAM_WEBHOOK_SECRET;return !!s&&req.headers.get("x-telegram-bot-api-secret-token")===s};
const admin=(q:any)=>{const chat=String(q?.message?.chat?.id||"");const ids=(process.env.TELEGRAM_ADMIN_USER_IDS||"").split(",").map(x=>x.trim()).filter(Boolean);return chat===String(process.env.TELEGRAM_CHAT_ID||"")&&ids.length>0&&ids.includes(String(q?.from?.id||""))};
const transitions:Record<string,string[]>={PENDING:["CONFIRMED","CANCELLED"],CONFIRMED:["PROCESSING","CANCELLED"],PROCESSING:["SHIPPED"],SHIPPED:["DELIVERED"],DELIVERED:[],CANCELLED:[],REFUNDED:[]};
async function callback(id:string,text:string,alert=false){await telegramApi("answerCallbackQuery",{callback_query_id:id,text,show_alert:alert})}
export async function POST(req:NextRequest){try{if(!allowed(req))return NextResponse.json({ok:false},{status:401});const u=await req.json();const q=u.callback_query;if(!q)return NextResponse.json({ok:true});if(!admin(q)){await callback(q.id,"Unauthorized",true);return NextResponse.json({ok:true})}const data=String(q.data||"");const parts=data.split(":");const action=parts[0],id=parts[1];const o=await db.order.findUnique({where:{id},include:{items:true,paymentGateway:true}});if(!o){await callback(q.id,"Order not found",true);return NextResponse.json({ok:true})}
if(action==="pay_confirm"){let confirmed=false;await db.$transaction(async tx=>{const current=await tx.order.findUnique({where:{id},select:{paymentStatus:true,paymentGatewayId:true,total:true,status:true,paymentReference:true}});if(!current||current.paymentStatus==="PAID")return;const ref=current.paymentReference||"TELEGRAM-CONFIRM-"+current.id;await tx.paymentTransaction.create({data:{orderId:id,gatewayId:current.paymentGatewayId!,reference:ref,amount:current.total,status:"PAID",rawResponse:{source:"telegram_admin_confirmation",telegramUserId:q.from?.id||null},verifiedAt:new Date()}});const changed=await tx.order.updateMany({where:{id,paymentStatus:"PENDING"},data:{paymentStatus:"PAID",status:"CONFIRMED",paymentReference:ref}});if(changed.count!==1)throw new Error("Payment state changed");await tx.stockReservation.updateMany({where:{orderId:id,status:"HELD"},data:{status:"CONFIRMED"}});await tx.auditLog.create({data:{action:"TELEGRAM_PAYMENT_CONFIRMED",entity:"Order",entityId:id,metadata:{telegramUserId:q.from?.id||null}}});confirmed=true});if(!confirmed){await callback(q.id,"Already paid or already processed",true)}else{await callback(q.id,"✅ Payment confirmed",true);await telegramApi("editMessageReplyMarkup",{chat_id:process.env.TELEGRAM_CHAT_ID,message_id:q.message?.message_id,reply_markup:{inline_keyboard:[]}});await notifyStatus(id)}}
else if(action==="pay_reject"){let rejected=false;await db.$transaction(async tx=>{const current=await tx.order.findUnique({where:{id},select:{paymentStatus:true,status:true}});if(!current||current.paymentStatus!=="PENDING")return;const changed=await tx.order.updateMany({where:{id,paymentStatus:"PENDING"},data:{paymentStatus:"FAILED",status:"CANCELLED"}});if(changed.count!==1)return;const rs=await tx.stockReservation.findMany({where:{orderId:id,status:"HELD"}});for(const r of rs)await tx.product.update({where:{id:r.productId},data:{stock:{increment:r.quantity}}});await tx.stockReservation.updateMany({where:{orderId:id,status:"HELD"},data:{status:"RELEASED"}});await tx.auditLog.create({data:{action:"TELEGRAM_PAYMENT_REJECTED",entity:"Order",entityId:id,metadata:{telegramUserId:q.from?.id||null}}});rejected=true});await callback(q.id,rejected?"❌ Payment rejected":"Order already processed",true);if(rejected){await telegramApi("editMessageReplyMarkup",{chat_id:process.env.TELEGRAM_CHAT_ID,message_id:q.message?.message_id,reply_markup:{inline_keyboard:[]}});await notifyStatus(id)}}
else if(action==="order_view"){const items=o.items.map(i=>"• "+esc(i.name)+" × "+i.quantity).join("\n");await telegramApi("sendMessage",{chat_id:process.env.TELEGRAM_CHAT_ID,text:"<b>Order Details</b>\nOrder: <code>"+esc(o.orderNumber)+"</code>\nCustomer: "+esc(o.customerName)+"\nPhone: <code>"+esc(o.customerPhone)+"</code>\nAddress: "+esc(o.shippingAddress)+"\nTotal: ৳"+Number(o.total).toLocaleString("en-BD")+"\nPayment: "+o.paymentStatus+"\nStatus: "+o.status+"\n\n"+items,parse_mode:"HTML"})}
else if(action==="status_menu"){await telegramApi("sendMessage",{chat_id:process.env.TELEGRAM_CHAT_ID,text:"Choose new status for <code>"+esc(o.orderNumber)+"</code>",parse_mode:"HTML",reply_markup:{inline_keyboard:[[{text:"✅ Confirmed",callback_data:"status:"+o.id+":CONFIRMED"},{text:"⚙️ Processing",callback_data:"status:"+o.id+":PROCESSING"}],[{text:"🚚 Shipped",callback_data:"status:"+o.id+":SHIPPED"},{text:"📬 Delivered",callback_data:"status:"+o.id+":DELIVERED"}],[{text:"❌ Cancelled",callback_data:"status:"+o.id+":CANCELLED"}]]}})}
else if(action==="status"){const target=parts[2];if(!transitions[o.status]?.includes(target)||(target==="CONFIRMED"&&o.paymentStatus!=="PAID")){await callback(q.id,"Invalid status transition",true);return NextResponse.json({ok:true})}await db.$transaction(async tx=>{await tx.order.update({where:{id},data:{status:target as any}});await tx.auditLog.create({data:{action:"TELEGRAM_ORDER_STATUS_CHANGED",entity:"Order",entityId:id,metadata:{from:o.status,to:target,telegramUserId:q.from?.id||null}}});if(target==="CANCELLED"&&o.paymentStatus==="PENDING"){const rs=await tx.stockReservation.findMany({where:{orderId:id,status:"HELD"}});for(const r of rs)await tx.product.update({where:{id:r.productId},data:{stock:{increment:r.quantity}}});await tx.stockReservation.updateMany({where:{orderId:id,status:"HELD"},data:{status:"RELEASED"}})}});await callback(q.id,"Status → "+target,true);await notifyStatus(id)}
return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"Telegram bot processing failed"},{status:400})}}
